### ISSUE TITLE
Matches overview should have a date next to it

### ISSUE THREAD

**Issue by thomascorthouts** [yvesgoeleven/BasketLummen#56]
Heard some complaints about the week overview (of matches) being confusing. A date next to the day should fix this issue

- [x] Check whether this a realistic feature
- [x] Implement the feature

**Comment by yvesgoeleven** [comment]
@thomascorthouts the date is available when we enable the column, so should be easy to visualize as well

**Comment by yvesgoeleven** [comment]
fixed in #a506af751759cccfa7a39f4ddad3ed1ec3095a85
